### ISSUE TITLE
One more thing...

### ISSUE THREAD

**Issue by deanott** [MNegus/SpinSystems#1]
# THE ONE THING
# THAT REALL
# GRIDFN S MY HJEDS ON GIHUB
# IS WHEN STUPID
# CHILDREN
# TRY TO USE IT
# AND DONT 
# DELETE THEIR FIELS 
# WITH THE FRICKIN
# THING
# -10/10 I WOULD NOT RECOMEND 

*love is all you need - David Cameron*

**Comment by MNegus** [comment]
Hello sir,

Go away
